/**
 * Full scene data converted from flowgame/scene_data.html
 * Schema:
 * Scene = {
 *   id: string,
 *   text: string,
 *   choices: Array<{ text: string, next: string }>,
 *   type: "STORY" | "MINIGAME" | "ENDING",
 *   effects: Record<string, string | number | boolean>
 * }
 */

export const INITIAL_STATE = {
  HP: 5,
  Karma: 0,
  ATK: 0,
  NL: 0,
  has_wife: false,
  saved_cats: false,
  currentSceneId: "A",
};

export const SCENES = [
  {
    id: "A",
    text: "Ngày 1 bắt đầu khi bạn gặp chủ lần đầu tiên. Trước mặt bạn mở ra một hướng đi quyết định cả cuộc đời.",
    choices: [{ text: "Tiếp tục", next: "B" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "B",
    text: "Chủ cho bạn sự an toàn, nhưng tự do ngoài đường vẫn vẫy gọi. Bạn phải chọn con đường ngay lúc này.",
    choices: [
      { text: "Trốn đi", next: "S0" },
      { text: "Đi theo chủ", next: "H0" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "S0",
    text: "Bạn chọn tuyến đường phố, nơi nguy hiểm luôn rình rập nhưng tự do thuộc về bạn. Cuộc chiến sinh tồn bắt đầu ngay lập tức.",
    choices: [{ text: "Tiếp tục", next: "S1" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S1",
    text: "Bạn thăm dò lãnh thổ để tìm thức ăn và chỗ ẩn nấp. Mỗi lựa chọn đều định hình cách bạn trưởng thành.",
    choices: [
      { text: "Lục khu thùng rác", next: "S1a" },
      { text: "Vào tuyến cống", next: "S1b" },
      { text: "Leo tuyến trên cây", next: "S1c" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "S1a",
    text: "Bạn kiếm ăn trong đống rác, cân bằng giữa đói khát và rủi ro. Ngày mới đẩy bạn đến những va chạm khắc nghiệt hơn.",
    choices: [{ text: "Sang ngày 2", next: "S2" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S1b",
    text: "Bạn chui qua cống và vật lộn để thoát khỏi mê cung ngột ngạt. Đường phố trở nên khắc nghiệt nhanh chóng.",
    choices: [{ text: "Sang ngày 2", next: "S2" }],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "S1c",
    text: "Bạn săn mồi từ trên cao và học cách ra đòn chớp nhoáng. Sự tự tin tăng lên khi áp lực lãnh thổ ngày càng lớn.",
    choices: [{ text: "Sang ngày 2", next: "S2" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S2",
    text: "Một băng mèo chặn đường và ép bạn phải phản ứng. Lựa chọn này quyết định quyền lực, trung thành hay chỉ là sống sót.",
    choices: [
      { text: "Đánh nhau (30%)", next: "S2a" },
      { text: "Gia nhập băng", next: "S2b" },
      { text: "Chạy trốn (100%)", next: "S2c" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "S2a",
    text: "Bạn chiến đấu và sống sót sau cuộc đụng độ, đầy thương tích nhưng sắc bén hơn. Ngày tiếp theo là lúc phục hồi sức mạnh.",
    choices: [{ text: "Tiếp tục", next: "S3" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S2b",
    text: "Bạn chấp nhận đời sống băng nhóm và bước vào hệ thống thứ bậc đường phố. Sự kiểm soát thay thế cho độc lập.",
    choices: [{ text: "Tiếp tục", next: "SD" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S2c",
    text: "Bạn rút lui để giữ tự do, nhưng đường phố vẫn không khoan nhượng. Bạn chuyển sang tự rèn luyện bản thân.",
    choices: [{ text: "Tiếp tục", next: "S3" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S3",
    text: "Bạn rèn luyện một mình và mở khóa sự tự tin mới. Một cuộc gặp gỡ tình cảm trở nên khả thi.",
    choices: [{ text: "Tiếp tục", next: "S4" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S4",
    text: "Bạn gặp một mèo cái, nhưng thành công phụ thuộc vào chuẩn bị và thời điểm. Đây là khoảnh khắc xã hội đầy rủi ro.",
    choices: [
      { text: "Tiếp cận trên mái nhà (70%)", next: "S4m" },
      { text: "Tiếp cận ngoài đường (100%)", next: "S4r" },
      { text: "Xông vào nhà (50%)", next: "S4h" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "S4m",
    text: "Trên mái nhà, căng thẳng dâng cao khi bạn thực hiện nước đi táo bạo. Chỉ một sai lầm cũng phải trả giá.",
    choices: [
      { text: "Thành công", next: "S4g" },
      { text: "Thất bại", next: "SF1" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "S4r",
    text: "Giữa đường phố, cách tiếp cận của bạn thẳng thắn và dứt khoát. Đà tâm lý đang nghiêng về phía bạn.",
    choices: [{ text: "Thành công", next: "S4g" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S4h",
    text: "Bạn ép cuộc gặp trong vùng nguy hiểm. Canh bạc này có thể mang về thắng lợi hoặc đòn trừng phạt.",
    choices: [
      { text: "Thành công", next: "S4g" },
      { text: "Thất bại", next: "SF1" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "SF1",
    text: "Bạn bị tát và mất HP, nhưng câu chuyện vẫn tiếp diễn. Bạn gượng dậy và tiến về phía trước.",
    choices: [{ text: "Tiếp tục", next: "S5" }],
    type: "STORY",
    effects: { HP: -1 },
  },
  {
    id: "S4g",
    text: "Bạn thành công và đời sống cá nhân bắt đầu thay đổi. Một tuyến drama ẩn có thể kích hoạt trước khi quay lại tuyến chính.",
    choices: [
      { text: "[Hệ thống] nếu has_wife=true, vào drama overlay", next: "D0" },
      { text: "[Hệ thống] ngược lại tiếp tục tuyến chính", next: "S5" },
    ],
    type: "MINIGAME",
    effects: { has_wife: true },
  },
  {
    id: "S5",
    text: "Bạn đụng phải bọn trộm mèo và hiểm nguy bùng nổ tức thì. Đây là một chốt sinh tồn quan trọng.",
    choices: [{ text: "Vào màn trốn trộm mèo", next: "S5a" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S5a",
    text: "Bạn cố thoát khỏi hỗn loạn và hoảng loạn. Kết quả sẽ quyết định bạn còn tự do hay không.",
    choices: [
      { text: "Thắng", next: "S6" },
      { text: "Thua / bị bắt", next: "S7" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "S6",
    text: "Bạn có cơ hội hành động vì điều lớn hơn bản thân. Quyết định lúc này định nghĩa hướng đạo đức của bạn.",
    choices: [
      { text: "Cứu những mèo khác", next: "S6a" },
      { text: "Tiếp tục sống cho bản thân", next: "S6b" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "S6a",
    text: "Bạn lao vào giải cứu và chấp nhận mạo hiểm tất cả vì đồng loại. Con đường này dẫn đến một ending anh hùng.",
    choices: [{ text: "Tiếp tục", next: "EC_H" }],
    type: "STORY",
    effects: { saved_cats: true },
  },
  {
    id: "S6b",
    text: "Bạn sống sót và tiếp tục con đường hoang theo cách của riêng mình. Đường phố vẫn thuộc về bạn.",
    choices: [{ text: "Tiếp tục", next: "EC" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S7",
    text: "Bạn bị nhốt trong lồng và đối mặt số phận tàn nhẫn. Thoát ra là cơ hội duy nhất.",
    choices: [{ text: "Cố thoát khỏi lồng", next: "S7a" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "S7a",
    text: "Bạn vùng vẫy để phá lồng trong áp lực nghẹt thở. Một kết quả cứu bạn, kết quả còn lại chấm dứt tất cả.",
    choices: [
      { text: "Thắng", next: "S6b" },
      { text: "Thua", next: "EX" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "SD",
    text: "Bạn leo lên quyền lực băng nhóm và kiểm soát khu phố. Tự do bị đánh đổi để lấy quyền thống trị.",
    choices: [{ text: "Tiếp tục", next: "ED" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H0",
    text: "Bạn chọn tuyến ở nhà, nơi an toàn cao nhưng tự do thu hẹp. Sự êm ấm luôn đi kèm cái giá riêng.",
    choices: [{ text: "Tiếp tục", next: "H1" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H1",
    text: "Bạn bước vào nhà và cuối cùng cũng được ăn no. Cảm giác an toàn bắt đầu định hình lại bản năng.",
    choices: [{ text: "Tiếp tục", next: "H2" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H2",
    text: "Bạn khám phá ngôi nhà và phát hiện những thói quen kỳ lạ dễ nghiện. Cuộc sống trong nhà vừa ấm áp vừa gò bó.",
    choices: [{ text: "Thử minigame cỏ mèo", next: "H2m" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H2m",
    text: "Bạn trôi vào cơn phê cỏ mèo hỗn loạn và mất kiểm soát. Phản ứng của chủ phụ thuộc vào kết quả của bạn.",
    choices: [
      { text: "Thắng", next: "H2w" },
      { text: "Thua", next: "H2l" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "H2w",
    text: "Bạn hồi lại trong trạng thái vui vẻ và chủ rất hài lòng. Sự gắn kết giữa hai bên mạnh lên.",
    choices: [{ text: "Tiếp tục", next: "H3" }],
    type: "STORY",
    effects: { HP: 1, Karma: 1 },
  },
  {
    id: "H2l",
    text: "Bạn gục xuống tệ hại và khiến chủ lo lắng. Sự ổn định trở nên mong manh.",
    choices: [{ text: "Tiếp tục", next: "H3" }],
    type: "STORY",
    effects: { HP: -1, Karma: -1 },
  },
  {
    id: "H3",
    text: "Ngày tắm xuất hiện như một cơn khủng hoảng. Bạn phải chống cự hoặc chịu đựng cơn hỗn loạn này.",
    choices: [{ text: "Vào trận chiến xà phòng", next: "H3m" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H3m",
    text: "Trận xà phòng thử thách khả năng kiểm soát và sức bền của bạn. Kết quả sẽ đổi hướng toàn bộ đà tâm lý.",
    choices: [
      { text: "Thắng", next: "H3w" },
      { text: "Thua", next: "H3l" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "H3w",
    text: "Bạn thoát ra tương đối khô ráo và khiến chủ nể phục. Sự tự tin trong nhà tăng cao.",
    choices: [{ text: "Tiếp tục", next: "H4" }],
    type: "STORY",
    effects: { HP: 1, ATK: 1, Karma: 1 },
  },
  {
    id: "H3l",
    text: "Bạn kết thúc trong trạng thái ướt sũng và bực bội, căng thẳng dâng lên. Ngày kế tiếp trở thành điểm rẽ lớn.",
    choices: [{ text: "Tiếp tục", next: "H4" }],
    type: "STORY",
    effects: { HP: -1, ATK: -1, Karma: -1 },
  },
  {
    id: "H4",
    text: "Ở phòng khám, số phận tách thành hai hướng rõ rệt. Đây là nhánh chính của tuyến ở nhà.",
    choices: [{ text: "Cố đào thoát khỏi phẫu thuật", next: "H4m" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H4m",
    text: "Bạn liều mình né thủ thuật trong một cuộc chạy trốn tuyệt vọng. Thắng nghĩa là tự do, thua nghĩa là bị giam hãm.",
    choices: [
      { text: "Thắng: thoát", next: "H5A" },
      { text: "Thua: bị thiến", next: "H5B" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "H5A",
    text: "Bạn trở lại thế giới bên ngoài với tự do phải trả giá bằng đau đớn. Bản năng sinh tồn thức dậy lần nữa.",
    choices: [{ text: "Săn chuột", next: "H5Am" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H5Am",
    text: "Bạn săn mồi ngoài trời và chạm lại nhịp sống hoang dã. Tuyến này khép lại bằng một ending tự do.",
    choices: [{ text: "Tiếp tục", next: "EC" }],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "H5B",
    text: "Bạn ở lại trong nhà, đã thay đổi và bị kiểm soát nhiều hơn. Xung đột thật sự giờ nằm trong nội tâm.",
    choices: [{ text: "Vào thử thách nằm im", next: "H5Bm" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "H5Bm",
    text: "Bạn đứng yên và cân nhắc bước kế tiếp dưới áp lực cuộc sống gia đình. Một hành động nhỏ sẽ định nghĩa Karma của bạn.",
    choices: [{ text: "Tiếp tục", next: "H6" }],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "H6",
    text: "Bạn quyết định nằm im hay bật ra khỏi khuôn khổ. Lựa chọn này trực tiếp làm lệch cán cân đạo đức.",
    choices: [
      { text: "Nằm im", next: "KPLUS" },
      { text: "Nhảy ra", next: "KMINUS" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "KPLUS",
    text: "Bạn chấp nhận sự kiềm chế và tăng Karma. Sự suy ngẫm trong bạn trở nên sâu hơn.",
    choices: [{ text: "Tiếp tục", next: "H7" }],
    type: "STORY",
    effects: { Karma: 1 },
  },
  {
    id: "KMINUS",
    text: "Bạn từ chối kiềm chế và mất Karma. Mâu thuẫn trong bạn trở nên cứng rắn hơn.",
    choices: [{ text: "Tiếp tục", next: "H7" }],
    type: "STORY",
    effects: { Karma: -1 },
  },
  {
    id: "H7",
    text: "Lập trường nội tâm cuối cùng quyết định ending tuyến ở nhà. Chấp nhận và phản kháng dẫn đến hai số phận khác nhau.",
    choices: [
      { text: "Chấp nhận", next: "EA" },
      { text: "Không chấp nhận", next: "EB" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "D0",
    text: "Một pha drama tình ái phủ lên tuyến chính của bạn. Hỗn loạn cá nhân bắt đầu đe dọa các quyết định sinh tồn.",
    choices: [{ text: "Tiếp tục", next: "D1" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "D1",
    text: "Bạn đối mặt lựa chọn tình cảm với hậu quả nặng nề. Mỗi bước đi đều làm rủi ro tăng lên.",
    choices: [
      { text: "Ngoại tình", next: "D2" },
      { text: "Theo dõi vợ", next: "D3" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "D2",
    text: "Bạn lén phản bội và hy vọng không bị phát hiện. Căng thẳng tăng vọt ngay lập tức.",
    choices: [
      { text: "Thành công", next: "D2a" },
      { text: "Bị bắt", next: "D2b" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "D2a",
    text: "Tạm thời bạn thoát được, nhưng ham muốn và rủi ro cùng lúc tăng cao. (Flow hiện chưa định nghĩa nút tiếp theo.)",
    choices: [{ text: "Chưa có nhánh tiếp theo trong flow gốc", next: "D2a" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "D2b",
    text: "Bạn bị lôi vào một cuộc đánh ghen bạo lực. Thắng hay thua đều sẽ thay đổi tất cả.",
    choices: [
      { text: "Thua", next: "EL" },
      { text: "Thắng", next: "D4" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "D3",
    text: "Bạn theo dõi vợ như một thám tử và khui ra sự thật giấu kín. Nghi ngờ chuyển thành xác nhận.",
    choices: [{ text: "Tiếp tục", next: "D4" }],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "D4",
    text: "Bạn phát hiện tình địch và buộc phải chọn cách xử lý. Cảm xúc và mưu lược va chạm trực diện.",
    choices: [{ text: "Tiếp tục", next: "D5" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "D5",
    text: "Bạn chọn bạo lực trực diện hoặc phá hoại bằng mưu kế. Cả hai con đường đều nguy hiểm.",
    choices: [
      { text: "Đánh trực diện", next: "D6" },
      { text: "Đầu độc qua nấu ăn", next: "D7" },
    ],
    type: "STORY",
    effects: {},
  },
  {
    id: "D6",
    text: "Bạn đối đầu tình địch bằng một trận móng vuốt sống còn. Sức mạnh quyết định số phận mối quan hệ.",
    choices: [
      { text: "Thành công", next: "D8" },
      { text: "Thất bại", next: "EL" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "D7",
    text: "Bạn thực hiện kế hoạch đầu độc đầy tính toán với rủi ro cao. Sai công thức lặp lại sẽ khiến mọi thứ sụp đổ.",
    choices: [
      { text: "Thành công", next: "D8" },
      { text: "Sai công thức 3 lần", next: "EL" },
    ],
    type: "MINIGAME",
    effects: {},
  },
  {
    id: "D8",
    text: "Bạn giành lại quyền kiểm soát đời sống tình cảm rồi quay lại hành trình chính. Câu chuyện nhập trở lại tuyến đường phố.",
    choices: [{ text: "Quay lại tuyến chính", next: "S6b" }],
    type: "STORY",
    effects: {},
  },
  {
    id: "EC_H",
    text: "Ending C-Hero: Bạn chọn ý nghĩa thay vì an toàn và trở thành kẻ giải cứu trên con đường hoang.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "EC",
    text: "Ending C: Bạn tiếp tục sống ngoài đường, tự do nhưng luôn phơi mình trước hiểm nguy.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "ED",
    text: "Ending D: Bạn trở thành đại ca khu phố, vừa đáng sợ vừa được nể phục trong thế giới băng nhóm.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "EX",
    text: "Ending X: Bạn không thể thoát khỏi cảnh giam cầm và bị đẩy tới một kết cục chí mạng.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "EA",
    text: "Ending A: Bạn chấp nhận chiếc lồng êm ái và ổn định trong cuộc sống yên tĩnh nhưng bị kiểm soát.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "EB",
    text: "Ending B: Bạn từ chối chấp nhận và mãi mắc kẹt trong xung đột bên trong chiếc lồng vàng.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "EL",
    text: "Ending Love: Tuyến drama sụp đổ và bạn mất cả mối quan hệ lẫn sức khỏe.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "EAQ",
    text: "Chất lượng Ending A phụ thuộc Karma: Karma cao thì ấm áp, Karma thấp thì cô độc.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "EBQ",
    text: "Chất lượng Ending B phụ thuộc Karma: Karma cao thì hé mở, Karma thấp thì khép kín.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
  {
    id: "MSG",
    text: "Thông điệp cuối: an toàn và tự do hiếm khi đi cùng nhau, và cô độc quá lâu có thể làm mất chính mình.",
    choices: [],
    type: "ENDING",
    effects: {},
  },
];

export const SCENE_MAP = Object.fromEntries(
  SCENES.map((scene) => [scene.id, scene])
);

